config/routes.rb
Rails.application.routes.draw do
  resources  :posters,
    only: %w{index create show new},
    path: "plaks"
  resources  :categories, only: "index" 

  get '/auth/:provider/callback', to: 'users#create'
  get '/logout', to: 'users#logout', as: :logout

  resource :profile, only: :show

  get "/home" => "home#index"
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many:posters 
  belongs_to:user
  
  def self.with_posters
  	return distinct(:categories).joins(:posters)
  end

end

app/models/poster.rb
class Poster < ActiveRecord::Base
  has_and_belongs_to_many :categories 
  belongs_to :user

  mount_uploader :ref_imagem, PosterImageUploader
  
  def self.filter(term: nil, category: nil)
    query = self
    if term
      query = QueryUtils.where_attr_like(query, QueryUtils.concatenate_attrs(:description, :title), term)
    end
    if category
      query = query.joins(:categories).where(categories_posters: {category_id: category})
    end
    query
  end

  def have_image?(type)
    @poster.ref_imagem &&
      @poster.ref_imagem.public_send(type.to_sym) &&
      @poster.ref_imagem.public_send(type.to_sym).url
  end
end

app/models/poster_image_uploader.rb
class PosterImageUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick

  version :large do
    process resize_to_fit: [640, nil] # Resize to specific width and adjust height
  end

  version :small do
    process resize_to_fit: [380, nil]
  end

  def store_dir
    "uploaded_posters/"
  end
end

app/models/query_utils.rb
module QueryUtils
  extend self

  def postgresql?
    adapter = ActiveRecord::Base.connection.adapter_name.downcase.to_sym
    adapter == :postgresql
  end

  def concatenate_attrs(*attrs)
    if QueryUtils.postgresql?
      attrs.map!{|attr| "COALESCE(#{attr}, '')"}
      concat = "(#{attrs.join(" || ")})"
    else
      attrs.map!{|attr| "IFNULL(#{attr}, '')"}
      concat = "CONCAT(#{attrs.join(",")})"
    end
    concat
  end

  def where_attr_like(query, attr, term)
    if postgresql?
      query.where("#{attr} ilike ?", "%#{term}%")
    else
      query.where("#{attr} like ?", "%#{term}%")
    end
  end
end

app/models/user.rb
# TEM QUE TIRAR OS RESCUES DOS MÉTODOS, POR QUE VAI PARAR DE DISPARAR ERROS
class User < ActiveRecord::Base
  has_many :posters 
  has_many :categories

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :trackable, :validatable

  def self.from_omniauth(auth_hash)
    info = auth_hash[:info]
    credentials = auth_hash[:credentials]
    raw = auth_hash[:extra][:raw_info]
    user = User.find_or_initialize_by(email: info[:email])
    user.id_facebook = auth_hash[:uid]
    user.name = info[:name]
    user.image = info[:image]
    user.location = info[:location]
    user.gender = raw[:gender]
    user.birthday = convert_birthday(raw[:birthday])
    user.facebook_token = credentials[:token]
    user
  rescue
    user
  end
private
  def self.convert_birthday(date_str)
    begin
      DateTime.strptime(date_str, "%m/%d/%Y")
    rescue
      DateTime.strptime(date_str, "%m/%d")
    end
  rescue
    nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  helper_method :logged_in?, :current_user

  def current_user=(user_id)
    session[:current_user] = user_id
  end

  def current_user
    User.find session[:current_user]
  end

  def logged_in?
    session[:current_user] != nil
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.with_posters
    respond_to do |format|
      format.json{ render json: @categories , :only => [:name] }
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.all
    @term = params[:term]
    @category = Category.find_by_name params[:category]
    @posters = Poster.filter(term: @term, category: @category)
      .page(params[:page])
      .per(params[:per_page])
      .order(created_at: :desc)
      #.where("date_expiration >= ? AND posters.disabled = ? ", Time.now, false )
  end
end

app/controllers/posters_controller.rb
class PostersController < ApplicationController

  def index
    @posters = Poster.filter(term: params[:term], category: params[:category])
      .page(params[:page])
      .per(params[:per_page])
      .where("date_expiration >= ? AND posters.disabled = ? ", Time.now, false )
      .order(created_at: :desc)
    respond_to do |format|
      format.json{ render json: @posters ,
        :only => [:id, :title , :description, :date_event, :ref_imagem],
        :include => {
          :categories => {only: :name}
        }
      }
    end
  end

  def create
    poster = Poster.new poster_params
    poster.date_expiration = Time.now + 30.days
    poster.disabled = false
    respond_to do |format|
      if poster.save!
        #PosterCreationNotifier.notify(email: params[:email], poster: poster).deliver!
        format.json{ head :ok }
        format.html{redirect_to "/plaks/#{poster.id}"}
      else
        @errors = poster.errors
        format.json{ render "errors" }
      end
    end
  end

  def show
    @poster = Poster.includes(:categories).find(params[:id])
    @image_url = @poster.ref_imagem.large.url
    respond_to do |format|
      format.html
      format.json{ render json: @poster,
      :include => {
        :categories => {only: :name}
      },
      :only => [
        :title, 
        :description, 
        :date_event, 
        :ref_imagem, 
        :theme, 
        :visibility_title,
        :visibility_description,
        :visibility_date_event,
        :date_expiration,
        :disabled,
      ]}
    end
  end

  def new
    @poster     = Poster.new
    @categories = Category.all
  end

private
  def poster_params
    params.require(:poster).permit(:title, :description, :date_event,
      :date_expiration, :visibility_title, :visibility_description,
      :visibility_date_event, :theme, :ref_imagem)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :check_login

  def show
    respond_to do |format|
      format.json { render json: current_user }
    end
  end

private
  def check_login
    unless logged_in?
      render text: "not-logged-in", status: :not_authorized
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    user = User.from_omniauth(auth_hash)
    if user.save
      self.current_user = user.id
      redirect_to home_path, notice: "Você está conectado."
    else
      logger.error %Q[Não conseguiu logar o usuário: #{user.inspect}
      Ocorreram os seguintes erros: #{user.errors.inspect}]
      redirect_to home_path, notice: "Falha ao conectar."
    end
  end

  def logout
    self.current_user = nil
    redirect_to home_path
  end

private
  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posters_helper.rb
module PostersHelper
  def image_presence_class(image_url)
    image_url ? "with-image" : "without-image"
  end
end

app/views/home/index.html.erb
<%= render partial: "layouts/home_topbar" %>

<div id="container-plakat">
	<%@posters.each do |poster|%>
		<a href="/plaks/<%=poster.id%>">
		<div class="item-plak">
			<img src="<%=poster.ref_imagem%>">
			<div class="item-plak-content">
				<h2><%=poster.title%></h2>
				<div class="item-plak-desc"><%=poster.description%></div>
				<% if poster.date_event %>
					<h6><b>Data do evento: </b><%=poster.date_event.strftime('%d/%m/%Y')%></h6>
				<% end -%>
			</div>
		</div>
		</a>
	<%end%>
</div>

app/views/layouts/_categories_items.html.erb
<% @poster.categories.each do |category| %>
  <li class="category-item list-item">
    <a href="#">
      <div class="list-item-front-shadow"></div>
			<span class="list-item-label"><%= category.name %></span>
      <div class="hyperlink-icon"><%= render partial: "layouts/hyperlink_svg" %></div>
    </a>
  </li>
<% end %>

app/views/layouts/_home_topbar.html.erb
<div class="topbar">
	<div class="back-home">
		<div class="plakat-logo">
      <a href="<%= home_path %>">
				<%= render partial: "layouts/plakat_svg" %>
			</a>
		</div>
	</div>
	<div class="topbar-middle">
    <% if @categories %>
		<div class="categories-btn-area list-wrapper">
			<div class="special-btn categories-btn open-list">
				<span class="special-btn-white-front"></span>
				<div class="btn-icon">
					<%= render partial: "layouts/menu_svg" %>
				</div>
        <span class="btn-label"><%= @category.nil? ? "Categorias" : @category.name %></span>
			</div>
			<ul class="all-categories-list vertical-list hidden-list">
        <li class="list-item">
          <a href="<%= home_path %>">
            <div class="list-item-front-shadow"></div>
            <span class="list-item-label">Todas</span>
          </a>
        </li>
        <% @categories.each do |category| %>
          <li class="list-item">
            <a href="<%= home_path(category: category.name) %>">
              <div class="list-item-front-shadow"></div>
              <span class="list-item-label"><%= category.name %></span>
            </a>
          </li>
        <% end -%>
			</ul>
		</div>
		<div class="search-area">
			<%= form_tag home_path, method: "GET", class: "pretty-search" do %>
				<div class="svg-btn">
					<%= render partial: "layouts/search_svg" %>
				</div>
        <input class="pretty-search-input" name="term" type="text" value="<%=@term%>" placeholder="Buscar plaks" />
        <%= hidden_field_tag("category", @category.name) unless @category.nil? %>
      <% end %>
		</div>
  <% end %>
	</div>
	<% if logged_in? %>
		<div class="list-wrapper">
			<div class="login-btn special-btn open-list">
				<span class="special-btn-white-front"></span>
				<div class="btn-icon">
					<img src="<%= current_user.image %>">
				</div>
				<span class="btn-label"><%= current_user.name.split(" ").first %></span>
			</div>
			<ul class="logged-menu vertical-list hidden-list">
				<li class="menu-option list-item">
					<a href="<%= new_poster_path %>">
						<div class="list-item-front-shadow"></div>
						<span class="list-item-label">Criar Plak</span>
					</a>
				</li>
				<li class="menu-option list-item">
					<a href="/plaks/list">
						<div class="list-item-front-shadow"></div>
						<span class="list-item-label">Meus plaks</span>
					</a>
				</li>
				<li class="menu-option list-item">
					<a href="<%= logout_path %>">
						<div class="list-item-front-shadow"></div>
						<span class="list-item-label">Logout</span>
					</a>
				</li>
			</ul>
		</div>
	<% else %>
		<div class="special-btn login-btn">
			<a class="btn-link" href="/auth/facebook"></a>
			<span class="special-btn-white-front"></span>
			<div class="btn-icon">
				<%= render partial: "layouts/login_svg" %>
			</div>
			<span class="btn-label">Login</span>
		</div>
	<% end %>
</div>

app/views/layouts/_hyperlink_svg.html.erb
<svg viewBox="0 0 24 24" height="100%" width="100%" preserveAspectRatio="xMidYMid meet" fit="" style="pointer-events: none; display: block;"><g><path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76 0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71 0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71 0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76 0 5-2.24 5-5s-2.24-5-5-5z"></path></g></svg>

app/views/layouts/_login_svg.html.erb
<svg viewBox="0 0 24 24" height="100%" width="100%" preserveAspectRatio="xMidYMid meet" fit="" style="pointer-events: none; display: block;"><g><path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"></path></g></svg>

app/views/layouts/_menu_svg.html.erb
<svg viewBox="0 0 24 24" height="100%" width="100%" preserveAspectRatio="xMidYMid meet" fit="" style="pointer-events: none; display: block;"><g><path d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z"></path></g></svg>

app/views/layouts/_plakat_svg.html.erb
  <svg viewBox="0 600 389.7 80" height="100%" width="100%" preserveAspectRatio="xMidYMid meet" fit="" style="pointer-events: none; display: block;">
<path id="symbol" d="M79,680H1c-0.6,0-1-0.4-1-1v-78c0-0.6,0.4-1,1-1h78c0.6,0,1,0.4,1,1v78C80,679.6,79.6,680,79,680z M64,648v-32 H16v32v16l16-16H64z M48,638H32v-12h16V638z"/>
<g id="typo">
    <path d="M109.6,649.1v20H96v-58.4h22.3c6.9,0,12.4,1.7,16.4,5.3s6.1,8.2,6.1,14c0,5.8-2.1,10.4-6.1,13.9 c-4.1,3.6-9.6,5.3-16.4,5.3L109.6,649.1L109.6,649.1z M109.6,638.7h8.7c2.9,0,5.2-0.9,6.8-2.5s2.3-3.7,2.3-6.3s-0.7-4.7-2.3-6.4 c-1.6-1.7-3.8-2.5-6.8-2.5h-8.7V638.7z"/>
    <path d="M162,658.7h25v10.4h-38.7v-58.4H162L162,658.7L162,658.7z"/>
    <path d="M225.7,657.7h-17.4l-3.3,11.4h-14.2l19-58.4h7.2l0,0l0,0h7.2l19.1,58.4h-14.2L225.7,657.7z M211.5,647.3h11.2 l-5.4-18.2H217L211.5,647.3z"/>
    <path d="M265,645.7h-3.8v23.4h-13.6v-58.4h13.6v22.8h2.8l13.3-22.8h17.1l-18.4,26.6l20,31.9h-17.4L265,645.7z"/>
    <path d="M330.7,657.7h-17.3l-3.3,11.4h-14.2l19-58.4h7.2l0,0l0,0h7.2l19.1,58.4h-14.2L330.7,657.7z M316.4,647.3h11.2 l-5.4-18.2H322L316.4,647.3z"/>
    <path d="M389.7,621.2h-15.5v48h-13.6v-48h-15.2v-10.4h44.2v10.4H389.7z"/>
</g>
</svg>

app/views/layouts/_search_svg.html.erb
<svg viewBox="0 0 24 24" height="100%" width="100%" preserveAspectRatio="xMidYMid meet" fit="" style="pointer-events: none; display: block;"><g><path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"></path></g></svg>

app/views/layouts/_share_svg.html.erb
<svg viewBox="0 0 24 24" height="100%" width="100%" preserveAspectRatio="xMidYMid meet" fit="" style="pointer-events: none; display: block;"><g><path d="M18 16.08c-.76 0-1.44.3-1.96.77L8.91 12.7c.05-.23.09-.46.09-.7s-.04-.47-.09-.7l7.05-4.11c.54.5 1.25.81 2.04.81 1.66 0 3-1.34 3-3s-1.34-3-3-3-3 1.34-3 3c0 .24.04.47.09.7L8.04 9.81C7.5 9.31 6.79 9 6 9c-1.66 0-3 1.34-3 3s1.34 3 3 3c.79 0 1.5-.31 2.04-.81l7.12 4.16c-.05.21-.08.43-.08.65 0 1.61 1.31 2.92 2.92 2.92 1.61 0 2.92-1.31 2.92-2.92s-1.31-2.92-2.92-2.92z"></path></g></svg>	

app/views/layouts/_toolbar.html.erb
<div class="topbar">
	<div class="back-home">
		<div class="plakat-logo">
			<a href="/home">
				<%= render partial: "layouts/plakat_svg" %>
			</a>
		</div>
	</div>
	<div class="categories topbar-middle">
	<% if @poster %>
		<div class="list-wrapper">
		<ul class="horizontal-list categories-horizontal-list">
			<%= render partial: "layouts/categories_items" %>
			<li class="extra-categories list-item open-list hidden-item">
				<span class="extra-categories-number"></span>
				<span class="extra-categories-mobile-label hidden-item">Categories</span>
			</li>
		</ul>
		<ul class="vertical-list categories-vertical-list hidden-list">
			<%= render partial: "layouts/categories_items" %>
		</ul>
		</div>
	<% end %> 	
	</div>
	<div class="special-btn share-btn">
		<span class="special-btn-white-front"></span>
		<div class="btn-icon">
			<%= render partial: "layouts/share_svg" %>
		</div>
		<span class="btn-label">Compartilhar</span>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Plakat</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= stylesheet_link_tag '//fonts.googleapis.com/css?family=RobotoDraft:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en', media: 'all'%>
	<%= yield :css %>
	<%= yield :metatags %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= yield :js %>
</body>
</html>

app/views/poster_creation_notifier/notify.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
  </head>
  <body>
    Novo poster criado!
    <p>Email: <%= @user_email %></p>
    <p>Título: <%= @poster.title %></p>
    <p>Descrição: <%= @poster.description %></p>
    <p>Data do evento: <%= @poster.date_event %></p>
    <p>Data de expiração: <%= @poster.date_expiration %></p>
    <p>Visibilidade do título: <%= @poster.visibility_title %></p>
    <p>Visibilidade da descrição: <%= @poster.visibility_description %></p>
    <p>Visibilidade da data do evento: <%= @poster.visibility_date_event %></p>
    <p>Tema: <%= @poster.theme %></p>
    <p>Imagem: <%= @poster.ref_imagem.url %></p>
  </body>
</html>

app/views/posters/new.html.erb
<%= render partial: "layouts/home_topbar" %>

<div class="new-poster">
    <%= form_for @poster, html: {multipart: true, id: "frm-pub-poster"} do |f| %>
        <%= f.text_field :title, placeholder: "Nome do cartaz", id: "title-poster", class: "span5" %>
        <%= f.collection_select :id, @categories, :id, :name, {:include_blank => '-- Selecione a categoria --'}, class: "span5", name: "poster[category_id]", id: "category_id" %>
        <%= f.text_area :description, placeholder: "Aqui você pode falar um pouco sobre seu plak, aquilo que você quer divulgar, comunicar, vender... #plakat #plak #info #engenharia #puc", id: "description-poster", class: "span10" %>
        <label class="span2">Data do evento: </label>
        <%= f.date_field :date_event, placeholder: "01/01/2015", id: "date-event-poster", class: "span3" %>
        <%= f.file_field :ref_imagem, id: "file-poster" , class: "span5" %>
        <button id="sub-poster" name="sub-poster">Publicar</button>
    <% end %>
</div>

app/views/posters/show.html.erb
<% content_for :metatags do %>
	<!-- for Facebook -->          
	<meta property="og:title" content="<%= @poster.title %>" />
	<meta property="og:type" content="article" />
	<meta property="og:image" content="<%= @image_url %>" />
	<meta property="og:url" content="<%= request.original_url %>" />
	<meta property="og:description" content="<%= @poster.description %>" />
<% end %>

<%= render partial: "layouts/toolbar" %>

<div class="plak <%= image_presence_class(@image_url) %>">
	<% if @image_url %>
		<div class="plak-image">
			<img src="<%= @image_url %>"></img>
		</div>
	<% end -%>

	<div class="plak-content">
		<h2 class="plak-title"><%= @poster.title %></h2>
		<p class="plak-description"><%= @poster.description %></p>
	</div>
</div>